= General Programming tasks =

This is a repository, where I store the tasks on my General Programming university course. 


== Task 1 ==

This task is dedicated to implementation of a Stack data structure in C programming language. The task is divided in several parts:

1. stack with capability to store only integer nubers;
2. stack with capability to store any type of data.

The both stacks have standard functionality to push (add an element), pop (delete an element), top (check the uppermost element), and create and desroy the stack.

The first part pf the task is completed in grindelf-stack-int header and source code files and simply stores integers as an array (a pointer to the integer value).

The second part is completed in grindelf-stack header and source code files and uses the 
[source, c]
----
void *
----
pointer to store the values of different types.

== Task 2 ==

The task is to create an implementation of a vector data structure in C programming language. Like the previous one the task is divided in several parts:

1. vector with capability to store only integer nubers;
2. vector with capability to store any type of data.

The both vectors have standard functionality to get data from the vector, to resize the vector, to append to the vector and to insert to the vector, as well as to create and to destroy the vector itself.
